### PR TITLE
Midterm

### PR DESCRIPTION
**Pull request by tack92**

### CODE REVIEW

**Comment by Chauncey203** [comment]
What does W.I.M.P stand for?

**Comment by Jadeynd** [comment]
I would like to see this question please:
What is an interface? 
a) the way users experience software or hardware

**Comment by Chauncey203** [comment]
Who said the medium is the message? 
A: McLuhan

**Comment by claudiacxw** [comment]
True or false, In a globalized world that focuses on the knowledge economy, is knowledge more valuable than resources?

a) True

**Pull request merged**
